CREATE TABLE BOOK (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	available BIT DEFAULT FALSE
);

insert into BOOK (id, available)
values (1,true);

insert into BOOK (id, available)
values (2,false);

insert into BOOK (id, available)
values (3,true);

insert into BOOK (id, available)
values (4,false);
