pipeline {

  agent any

  stages {
    stage('SDK - build and test') {
        steps {
            dir('library-monolith') {
                sh './gradlew check'
                step([$class: 'JacocoPublisher', execPattern:'build/jacoco/*.exec', classPattern: 'build/classes/main', sourcePattern: 'src/main/java'])
            }
        }
    }

    stage('SDK - package') {
        steps {
            dir('library-monolith') {
                sh './gradlew jar'
            }
        }
    }
  }

  post {
      success {
        archive 'library-monolith/build/**/library-*.jar'
      }
      always {
        junit 'library-monolith/build/test-results/**/*.xml'
      }
  }

}
